import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import { Raleway } from "next/font/google";

// Initialize Raleway font
const raleway = Raleway({
  subsets: ["latin"], // you can add "latin-ext" if needed
  weight: ["400", "500", "700"], // choose the weights you need
  variable: "--font-raleway", // optional, if you want CSS variable
});

export const metadata: Metadata = {
  title: "ScaleUp",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${raleway.className}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
